[font]
size = 11.0

[font.normal]
family = "Jetbrains Mono"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 25
y = 25

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.15

  [cursor.style]
  #shape = "Underline"
   shape = "Block"
  #shape = "Beam"
  blinking = "Always"
