###############################################################################
# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!
###############################################################################

general {
        colors = true
        interval = 5
        color_good = "#00FF00" # Green
        color_degraded = "#fafe7c" # Light yellow
        color_bad = "#ff7770" # Light red
}

order += "disk /home"
order += "disk /"
order += "memory"
order += "wireless _first_"
order += "cpu_temperature 0"
order += "cpu_usage"
order += "volume master"
order += "battery all"
order += "tztime local"


disk "/home" {
    format = " %avail "
}

cpu_temperature 0 {
	format                 = " %degrees °C "
	path                   = "/sys/class/thermal/thermal_zone0/temp"
	max_threshold          = 75
	format_above_threshold = " %degrees ⁰C "
	separator              = false
}

cpu_usage {
	format                 = " %usage "
	max_threshold          = 75
	format_above_threshold = " %usage "
	separator              = false
}


wireless _first_ {
        format_up = " [%quality at %essid, %bitrate / %frequency] "
        format_down = " Down "
}

battery all {
    format = "%status %percentage "
    status_chr = "⚡️"
    status_bat = ""
    status_unk = "♻"
    status_full = ""
    low_threshold = 15
    threshold_type = percentage
    integer_battery_capacity = true
    last_full_capacity = true
}

volume master {
        format = "🔊 %volume "
        format_muted = "🔈 Muted "
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}

disk "/" {
        format = " %avail "
}

memory {
        format = " %used | %available "
        threshold_degraded = "1G"
        format_degraded = "MEMORY < %available "
}

tztime local {
        format = " %d-%m-%Y   %H:%M%p"
}
