# Start i3bar to display a workspace bar (plus the system information i3status if available)
bar {
       status_command i3status -c /home/$USER/.config/i3/i3status/i3status.conf
       position bottom
        
# Please set your primary output first. Example: 'xrandr --output eDP1 --primary'
	    tray_output primary
	    #tray_output none
        tray_padding 0   
		    
# When strip_workspace_numbers is set to yes, any workspace that has a name of the form \“[n][:][NAME]” will display only the name.
       strip_workspace_numbers yes
       #strip_workspace_name no		        
       	               	    
    colors {
#       bar                  bground  
		background	         #0c0e0f
		statusline	         #ffffff
		focused_statusline   #ffffff
		focused_separator    #444444

#       workclass	           border      bground    text
        focused_workspace      #0c0e0f     #0c0e0f    #ffffff
        active_workspace       #0c0e0f     #0c0e0f    #ffffff
        inactive_workspace     #0c0e0f     #0c0e0f    #2F3D44
        urgent_workspace       #e53935     #e53935    #ffffff
        binding_mode           #0c0e0f     #0c0e0f    #ffffff  	           
      }
}

# Define colors for windows
# class                   border         bground     text        indicator      child_border
  client.focused          #556064        #556064     #ffffff     #454948        #556064
  client.focused_inactive #2F3D44        #2F3D44     #ffffff     #454948        #2F3D44
  client.unfocused        #2F3D44        #2F3D44     #ffffff     #454948        #2F3D44
  client.urgent           #e53935        #e53935     #ffffff     #e1b700        #e1b700
  client.placeholder      #000000        #000000     #ffffff     #000000        #000000

  client.background      #0c0e0f
