###################
# windows
###################

# Default i3 tiling mode
workspace_layout default

# Border indicator on windows
default_border pixel 1
default_floating_border normal 

# Bide borders
hide_edge_borders none

# Change borders
bindsym $mod+u border none
bindsym $mod+y border pixel 1

# Use Mouse+$mod to drag floating windows
floating_modifier $mod

# Default title format
for_window [class=".*"] title_format "  %title"

###################
## i3 Optional Key Bind
###################

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3
bindsym $mod+Shift+r restart

# display
bindsym XF86Display exec "~/.config/i3/scripts/detect_displays.sh"


###################
## i3 Application Key Bind
###################

# exit i3 (logs you out of your X session)
#bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# Screenshots in files
bindsym Print exec --no-startup-id maim --format=png "/home/$USER/Pictures/Screenshots/screenshot-$(date -u +'%Y%m%d-%H%M%SZ')-all.png"
bindsym shift+Print exec --no-startup-id maim --format=png --window $(xdotool getactivewindow) "/home/$USER/Pictures/Screenshots/screenshot-$(date -u +'%Y%m%d-%H%M%SZ')-current.png"
bindsym $mod+Print exec --no-startup-id maim --format=png --select "/home/$USER/Pictures/Screenshots/screenshot-$(date -u +'%Y%m%d-%H%M%SZ')-selected.png"

# Screenshots in clipboards
bindsym Ctrl+Print exec --no-startup-id maim --format=png | xclip -selection clipboard -t image/png
bindsym Ctrl+$mod+Print exec --no-startup-id maim --format=png --window $(xdotool getactivewindow) | xclip -selection clipboard -t image/png
bindsym Ctrl+Shift+Print exec --no-startup-id maim --format=png --select | xclip -selection clipboard -t image/png



