exec --no-startup-id desktop-items
#exec --no-startup-id xfsettingsd
exec --no-startup-id xfce4-power-manager
exec --no-startup-id source ~/.fehbg
exec --no-startup-id xrdb -merge ~/.Xresource
exec --no-startup-id xautolock -time 10 -locker 'betterlockscreen -l dim' -detectsleep
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec_always --no-startup-id dunst -config ~/.config/dunst/dunstrc
exec_always --no-startup-id ff-theme-util
exec_always --no-startup-id setcrsor
exec_always --no-startup-id conkypywalcolors.sh
exec_always killall polybar
#exec --no-startup-id "blueman-applet"
#exec --no-startup-id nm-applet &
exec_always --no-startup-id numlockx on
#exec_always --no-startup-id sleep 1 && feh --bg-fill ~/.config/i3/wallpapers/wall-01.png
exec --no-startup-id xset s 480 dpms 600 600 600
exec_always --no-startup-id picom --config ~/.config/picom/picom.conf -b
exec --no-startup-id "systemctl --user start i3-cycle-focus"
exec_always --no-startup-id autotiling

# Trackpad: natural scrolling, speed, tap support
exec --no-startup-id xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' 'libinput Natural Scrolling Enabled' 1
exec --no-startup-id xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' 'libinput Accel Speed' .8
exec --no-startup-id xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' 'libinput Tapping Enabled' 1

# Launch Polybar
exec_always --no-startup-id "wal -R && $HOME/.config/polybar/launch.sh"
