# Autostart applications/services on login   
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1     
exec --no-startup-id desktop-items
exec --no-startup-id start_conky_live_green
#exec --no-startup-id start_conky_maia
exec --no-startup-id xfce4-power-manager
exec --no-startup-id xfsettingsd --sm-client-disable &
exec --no-startup-id xautolock -time 10 -locker 'betterlockscreen -l dim' -detectsleep
exec_always --no-startup-id dunst -config ~/.config/dunst/dunstrc
exec_always --no-startup-id ff-theme-util
exec_always --no-startup-id setcursor
#exec --no-startup-id "blueman-applet"
exec_always --no-startup-id numlockx on
exec_always --no-startup-id sleep 1 && feh --bg-fill ~/.config/i3/wallpaper/wall-01.jpg
exec --no-startup-id xset s 480 dpms 600 600 600
#exec_always --no-startup-id picom -b
exec_always --no-startup-id picom --config ~/.config/picom/picom.conf -b




