[files]
recent_files=/home/ammarah/.config/networkmanager-dmenu/config.ini;/home/ammarah/.config/mimeapps.list;/home/ammarah/.config/pavucontrol.ini;/home/ammarah/.config/user-dirs.dirs;/home/ammarah/.config/user-dirs.locale;/home/ammarah/.zshrc;/home/ammarah/OneDrive/Linux/useful-commands;/home/ammarah/OneDrive/git-hub-token;/home/ammarah/Desktop/Test.java;/home/ammarah/.config/i3/config.d/i3.conf;
recent_projects=
current_page=2
FILE_NAME_0=55;Java;0;EUTF-8;1;1;0;%2Fhome%2Fammarah%2FDesktop%2FJava-Programs%2FCountCharacter.java;0;4
FILE_NAME_1=413;Java;0;EUTF-8;1;1;0;%2Fhome%2Fammarah%2FDesktop%2FTest.java;0;4
FILE_NAME_2=40;None;0;EUTF-8;1;1;0;%2Fhome%2Fammarah%2FOneDrive%2Fgit-hub-token;0;4

[project]
session_file=
project_file_path=/home/ammarah/projects

[geany]
treeview_position=0
msgwindow_position=518
geometry=0;0;1366;752;0;
sidebar_page=1

[VTE]
last_dir=/home/ammarah

[search]
find_all_expanded=true
replace_all_expanded=false
position_find_x=744
position_find_y=369
position_replace_x=-1
position_replace_y=-1
position_fif_x=362
position_fif_y=217

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=/usr/lib/geany/saveactions.so;
